# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CS116
course: CS116
semester: spring
year: 2019
syllabus: assets/syllabus.pdf
instructor: {
  name: "Boris Glavic",
  email: bglavic@iit.edu,
  webpage: "http://www.cs.iit.edu/~glavic/",
  phone: 312 567 5205,
  room: "206b",
  officehours: "Mondays, 12:00-1:00pm"
  }
tas:
  - name: TA1
    email: ta@iit.edu
    webpage: "http://www.cs.iit.edu/~glavic/"
    phone: 312 312 312
    office: SB 205
    officehours: Mondays, 10-11
  - name: TA2
description: >- # this means to ignore newlines until "baseurl:"
  This is the webpage for CS116.
baseurl: "/~cs116" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username: IITDBGroup
github_repos:  IITDBGroup/CS116

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-jupyter-notebook


# default frontmatter
defaults:
  - scope:
      path: "_pages"
    values:
      layout: "page"
  - scope:
      path: "notebooks"
    values:
      layout: "notebook"


# include static pages
include: [ "notebooks" ]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - bin
  - scripts
  - notebooks/startNotebook.sh
  - notebooks/killNotebook.sh
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
